### ISSUE TITLE
Markdown.vim not loaded and executed while launching SpaceVim editor. 

### ISSUE THREAD

**Issue by linusjf** [SpaceVim/vim-markdown#3]
https://github.com/SpaceVim/vim-markdown/blob/master/plugin/markdown.vim

The above file and its vim code does not appear to be loaded and executed when launching SpaceVim for a markdown file.

The three variables are not defined as needed.

This causes an error while launching the editor since ftplugin/markdown.vim needs the following variable to be defined:

```vim
if g:markdown_default_mappings
    inoremap <buffer> <C-b> ****<Left><Left>
endif
```
Platform: SpaceVim on Termux.

**Comment by linusjf** [comment]
My current fix is to paste the contents of plugin/markdown.vim into ftplugin/markdown.vim.

**Comment by wsdjeg** [comment]
@Fernal73 files in `plugin/*` are loaded before `ftplugin`, so this should be a issue.

**Comment by linusjf** [comment]
> @Fernal73 files in `plugin/*` are loaded before `ftplugin`, so this should be a issue.

Has this been fixed or is there a problem with my configuration for SpaceVim? 
This is being launched via the .cache directory created by SpaceVim. Should this be recreated? SPUpdate did not fix the issue. 
In that case, my current fix stays.

**Comment by wsdjeg** [comment]
It seems there is some issue with your configuration , please update spacevim. and I can not reproduce it.
--------------
wsdjeg

**Comment by linusjf** [comment]
Deleting vimfiles under .cache dir does not resolve the issue either.

I have no idea why you can't reproduce the error. I'm seemingly able to
reproduce it at will.
